version: '3.8'
services:
  nginx:
    build: ./docker/nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./docker/nginx/sites-available:/etc/nginx/sites-available
      - ./docker/nginx/configs/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/logs:/var/log/nginx
      - ./src:/var/www
    depends_on:
      - php

  php:
    build: ./docker/php
    container_name: php
    restart: always
    volumes:
      - ./docker/php/supervisor/supervisor.conf:/etc/supervisor/supervisord.conf
      - ./docker/php/supervisor/supervisor-programs.conf:/etc/supervisor/conf.d/app.conf
      - ./docker/php/configs:/usr/local/etc/php/conf.d
      - ./src:/var/www
    depends_on:
      - redis
      - mongo
      - postgres

  postgres:
    build: ./docker/postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: mvbsoft
      POSTGRES_USER: mvbsoft
      POSTGRES_PASSWORD: mvbsoft_postgres
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: mvbsoft
      MONGO_INITDB_ROOT_USERNAME: mvbsoft
      MONGO_INITDB_ROOT_PASSWORD: mvbsoft_mongo
    volumes:
      - ./docker/mongodb/data:/data/db
    ports:
      - "27017:27017"
      - "27018:27018"
      - "27019:27019"

  redis:
    build: ./docker/redis
    container_name: redis
    restart: always
    sysctls:
      - net.core.somaxconn=511
    ports:
      - "6379:6379"