#!/usr/bin/env php
<?php

use console\Configurator;

$basePath = __DIR__;

require $basePath . '/constants.php';
require $basePath . '/vendor/autoload.php';
require $basePath . '/vendor/yiisoft/yii2/Yii.php';
require $basePath . '/aliases.php';

$configs = Configurator::build();

$application = new yii\console\Application($configs);

$exitCode = $application->run();

exit($exitCode);